---
language: go
os:
  - linux

go:
  - "1.8"
  - "1.9"
  - "1.10"

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/DATA-DOG/godog/cmd/godog

install:
  - glide install

script:
  - go vet -v $(go list ./... | grep -v /vendor/)
  - godog
